language: python

matrix:
  include:
    - { python: 2.7, env: TOXENV=py27-dj111 }
    - { python: 2.7, env: TOXENV=py27-dj111-grp }
    - { python: 3.6, env: TOXENV=py36-dj111 }
    - { python: 3.6, env: TOXENV=py36-dj21 }
    - { python: 3.6, env: TOXENV=py36-dj21-grp }
    - { python: 3.6, dist: xenial, env: TOXENV=py36-dj22 }
    - { python: 3.6, dist: xenial, env: TOXENV=py36-dj30 }

cache:
  pip: true
  directories:
    - node_modules
    - bin

addons:
  chrome: stable

env:
  global:
    - PATH=$HOME/bin:$PATH
    - PIXELMATCH_BIN=$TRAVIS_BUILD_DIR/node_modules/.bin/pixelmatch
    - DATABASE_URL=sqlite:////tmp/test.db

before_script:
  - mkdir -p ~/bin
  - |
    if [ ! -e ~/bin/chromedriver ]; then
      export CHROMEDRIVER_VERSION=$(curl -q http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
      wget -N http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -P ~/
      unzip ~/chromedriver_linux64.zip -d ~/bin
      rm ~/chromedriver_linux64.zip
      chmod +x ~/bin/chromedriver
    fi

before_install:
  - nvm install 11
  - nvm use 11
  - travis_retry travis_retry npm install
  - travis_retry travis_retry npm install codecov
  - travis_retry travis_retry npm install pixelmatch
  - NODE_ENV=test npm run build

install:
  - pip install tox coverage codecov

script:
  - |
    travis_retry travis_retry travis_retry tox -- \
      --selenium=chrome-headless \
      --verbosity=2 \
      --failfast
  - npm run report
  - npm run codecov
  - coverage xml
  - codecov -F python

sudo: false
